### ISSUE TITLE
The code for contrastive learning

### ISSUE THREAD

**Issue by dilint** [thebestannie/Detection-free-MICCAI2023#2]
Hello, We are very interested in the detection-free pipeline mentioned in your paper. However, in addition to the pooling transformer mentioned in the previous issue, the code for unsupervised training of the backbone is not provided. We would like to implement this method on our own dataset. If we can obtain the original training code, we may be able to achieve better performance.

**Comment by bittersweet1999** [comment]
Thanks for your attention, for the unsupervised training method, we just follow the Mocov2, as mentioned in the paper, see in here https://github.com/facebookresearch/moco, you can directly use the official code. And for an updated code version, please refer to here https://github.com/bittersweet1999/cervical-cancer/issues/6, we provided a detailed guidance. And feel free to contact me if you have any other questions.

**Comment by dilint** [comment]
Thank you for your reply.

**Comment by dilint** [comment]
Thank you for your reply. The command for moco is following:
`python main_moco.py \
  -a resnet50 \
  --lr 0.03 \
  --batch-size 256 \
  --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
  [your imagenet-folder with train and val folders]`
And I still have a few questions: 
1. The backbone used is resnet50 or resnet34? 
2. Is data augmentation changed? 
3. Is any other hyper-parameter changed?
Thank you for your patience.

**Comment by bittersweet1999** [comment]
1. We test both resnet50 and resnet34, and found 50 is better.
2. No used the same augmentation way.
3. the lr we used was 1e-3, 0.03 may be a lit bit large but you can try and see.
But I think you can directly use the pretrained moco resnet I provided in the link, or you just want to have some method innovation in moco pretraining for pathology images?

**Comment by dilint** [comment]
Thank you very much for your previous answer, which has solved my confusion. However, unsupervised training of ResNet50 with over 100W images is a time-consuming task. Could you tell me approximately how long it took to conduct the pre-training experiment on what type of GPU?

**Comment by bittersweet1999** [comment]
Yes unsupervised pretraining is a time-consuming work, how many epochs are you prepared to train? if you follow the official as 200 epochs, we used 8 A100 trained for around 36 hours. Actually, I suggest that you can try not to train from scratch, you can resume the mocov2 model as in here https://dl.fbaipublicfiles.com/moco/moco_checkpoints/moco_v2_200ep/moco_v2_200ep_pretrain.pth.tar, may have a better time consumption.

**Comment by dilint** [comment]
Your reply has been very helpful to me. Thank you again for your time and patience.
